# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _capi
else:
    import _capi

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _capi.SWIG_PyInstanceMethod_New
_swig_new_static_method = _capi.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


link2obj = _capi.link2obj
obj2link = _capi.obj2link
get_from_kernel = _capi.get_from_kernel
inet_get_conf = _capi.inet_get_conf
rtnl_scope2str = _capi.rtnl_scope2str
rtnl_str2scope = _capi.rtnl_str2scope
rtnl_link_alloc = _capi.rtnl_link_alloc
rtnl_link_get = _capi.rtnl_link_get
rtnl_link_get_by_name = _capi.rtnl_link_get_by_name
rtnl_link_build_add_request = _capi.rtnl_link_build_add_request
rtnl_link_add = _capi.rtnl_link_add
rtnl_link_build_change_request = _capi.rtnl_link_build_change_request
rtnl_link_change = _capi.rtnl_link_change
rtnl_link_build_delete_request = _capi.rtnl_link_build_delete_request
rtnl_link_delete = _capi.rtnl_link_delete
rtnl_link_build_get_request = _capi.rtnl_link_build_get_request
rtnl_link_stat2str = _capi.rtnl_link_stat2str
rtnl_link_str2stat = _capi.rtnl_link_str2stat
rtnl_link_flags2str = _capi.rtnl_link_flags2str
rtnl_link_str2flags = _capi.rtnl_link_str2flags
rtnl_link_operstate2str = _capi.rtnl_link_operstate2str
rtnl_link_str2operstate = _capi.rtnl_link_str2operstate
rtnl_link_mode2str = _capi.rtnl_link_mode2str
rtnl_link_str2mode = _capi.rtnl_link_str2mode
rtnl_link_set_qdisc = _capi.rtnl_link_set_qdisc
rtnl_link_get_qdisc = _capi.rtnl_link_get_qdisc
rtnl_link_set_name = _capi.rtnl_link_set_name
rtnl_link_get_name = _capi.rtnl_link_get_name
rtnl_link_set_flags = _capi.rtnl_link_set_flags
rtnl_link_unset_flags = _capi.rtnl_link_unset_flags
rtnl_link_get_flags = _capi.rtnl_link_get_flags
rtnl_link_set_mtu = _capi.rtnl_link_set_mtu
rtnl_link_get_mtu = _capi.rtnl_link_get_mtu
rtnl_link_set_txqlen = _capi.rtnl_link_set_txqlen
rtnl_link_get_txqlen = _capi.rtnl_link_get_txqlen
rtnl_link_set_ifindex = _capi.rtnl_link_set_ifindex
rtnl_link_get_ifindex = _capi.rtnl_link_get_ifindex
rtnl_link_set_family = _capi.rtnl_link_set_family
rtnl_link_get_family = _capi.rtnl_link_get_family
rtnl_link_set_arptype = _capi.rtnl_link_set_arptype
rtnl_link_get_arptype = _capi.rtnl_link_get_arptype
rtnl_link_set_addr = _capi.rtnl_link_set_addr
rtnl_link_get_addr = _capi.rtnl_link_get_addr
rtnl_link_set_broadcast = _capi.rtnl_link_set_broadcast
rtnl_link_get_broadcast = _capi.rtnl_link_get_broadcast
rtnl_link_set_link = _capi.rtnl_link_set_link
rtnl_link_get_link = _capi.rtnl_link_get_link
rtnl_link_set_master = _capi.rtnl_link_set_master
rtnl_link_get_master = _capi.rtnl_link_get_master
rtnl_link_set_operstate = _capi.rtnl_link_set_operstate
rtnl_link_get_operstate = _capi.rtnl_link_get_operstate
rtnl_link_set_linkmode = _capi.rtnl_link_set_linkmode
rtnl_link_get_linkmode = _capi.rtnl_link_get_linkmode
rtnl_link_get_ifalias = _capi.rtnl_link_get_ifalias
rtnl_link_set_ifalias = _capi.rtnl_link_set_ifalias
rtnl_link_get_num_vf = _capi.rtnl_link_get_num_vf
rtnl_link_get_stat = _capi.rtnl_link_get_stat
rtnl_link_set_stat = _capi.rtnl_link_set_stat
rtnl_link_set_type = _capi.rtnl_link_set_type
rtnl_link_get_type = _capi.rtnl_link_get_type
rtnl_link_enslave = _capi.rtnl_link_enslave
rtnl_link_release = _capi.rtnl_link_release
class vlan_map(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    vm_from = property(_capi.vlan_map_vm_from_get, _capi.vlan_map_vm_from_set)
    vm_to = property(_capi.vlan_map_vm_to_get, _capi.vlan_map_vm_to_set)
    __swig_destroy__ = _capi.delete_vlan_map

# Register vlan_map in _capi:
_capi.vlan_map_swigregister(vlan_map)

VLAN_PRIO_MAX = _capi.VLAN_PRIO_MAX
rtnl_link_vlan_flags2str = _capi.rtnl_link_vlan_flags2str
rtnl_link_vlan_str2flags = _capi.rtnl_link_vlan_str2flags
rtnl_link_vlan_set_id = _capi.rtnl_link_vlan_set_id
rtnl_link_vlan_get_id = _capi.rtnl_link_vlan_get_id
rtnl_link_vlan_set_flags = _capi.rtnl_link_vlan_set_flags
rtnl_link_vlan_unset_flags = _capi.rtnl_link_vlan_unset_flags
rtnl_link_vlan_get_flags = _capi.rtnl_link_vlan_get_flags
rtnl_link_vlan_set_ingress_map = _capi.rtnl_link_vlan_set_ingress_map
rtnl_link_vlan_get_ingress_map = _capi.rtnl_link_vlan_get_ingress_map
rtnl_link_vlan_set_egress_map = _capi.rtnl_link_vlan_set_egress_map
rtnl_link_vlan_get_egress_map = _capi.rtnl_link_vlan_get_egress_map
rtnl_link_macvlan_alloc = _capi.rtnl_link_macvlan_alloc
rtnl_link_is_macvlan = _capi.rtnl_link_is_macvlan
rtnl_link_macvlan_mode2str = _capi.rtnl_link_macvlan_mode2str
rtnl_link_macvlan_str2mode = _capi.rtnl_link_macvlan_str2mode
rtnl_link_macvlan_flags2str = _capi.rtnl_link_macvlan_flags2str
rtnl_link_macvlan_str2flags = _capi.rtnl_link_macvlan_str2flags
rtnl_link_macvlan_set_mode = _capi.rtnl_link_macvlan_set_mode
rtnl_link_macvlan_get_mode = _capi.rtnl_link_macvlan_get_mode
rtnl_link_macvlan_set_flags = _capi.rtnl_link_macvlan_set_flags
rtnl_link_macvlan_unset_flags = _capi.rtnl_link_macvlan_unset_flags
rtnl_link_macvlan_get_flags = _capi.rtnl_link_macvlan_get_flags
VXLAN_ID_MAX = _capi.VXLAN_ID_MAX
rtnl_link_vxlan_alloc = _capi.rtnl_link_vxlan_alloc
rtnl_link_is_vxlan = _capi.rtnl_link_is_vxlan
rtnl_link_vxlan_set_id = _capi.rtnl_link_vxlan_set_id
rtnl_link_vxlan_get_id = _capi.rtnl_link_vxlan_get_id
rtnl_link_vxlan_set_group = _capi.rtnl_link_vxlan_set_group
rtnl_link_vxlan_get_group = _capi.rtnl_link_vxlan_get_group
rtnl_link_vxlan_set_link = _capi.rtnl_link_vxlan_set_link
rtnl_link_vxlan_get_link = _capi.rtnl_link_vxlan_get_link
rtnl_link_vxlan_set_local = _capi.rtnl_link_vxlan_set_local
rtnl_link_vxlan_get_local = _capi.rtnl_link_vxlan_get_local
rtnl_link_vxlan_set_ttl = _capi.rtnl_link_vxlan_set_ttl
rtnl_link_vxlan_get_ttl = _capi.rtnl_link_vxlan_get_ttl
rtnl_link_vxlan_set_tos = _capi.rtnl_link_vxlan_set_tos
rtnl_link_vxlan_get_tos = _capi.rtnl_link_vxlan_get_tos
rtnl_link_vxlan_set_learning = _capi.rtnl_link_vxlan_set_learning
rtnl_link_vxlan_get_learning = _capi.rtnl_link_vxlan_get_learning
rtnl_link_vxlan_enable_learning = _capi.rtnl_link_vxlan_enable_learning
rtnl_link_vxlan_disable_learning = _capi.rtnl_link_vxlan_disable_learning
rtnl_link_vxlan_set_ageing = _capi.rtnl_link_vxlan_set_ageing
rtnl_link_vxlan_get_ageing = _capi.rtnl_link_vxlan_get_ageing
rtnl_link_vxlan_set_limit = _capi.rtnl_link_vxlan_set_limit
rtnl_link_vxlan_get_limit = _capi.rtnl_link_vxlan_get_limit
rtnl_link_vxlan_set_port_range = _capi.rtnl_link_vxlan_set_port_range
rtnl_link_vxlan_get_port_range = _capi.rtnl_link_vxlan_get_port_range
rtnl_link_vxlan_set_proxy = _capi.rtnl_link_vxlan_set_proxy
rtnl_link_vxlan_get_proxy = _capi.rtnl_link_vxlan_get_proxy
rtnl_link_vxlan_enable_proxy = _capi.rtnl_link_vxlan_enable_proxy
rtnl_link_vxlan_disable_proxy = _capi.rtnl_link_vxlan_disable_proxy
rtnl_link_vxlan_set_rsc = _capi.rtnl_link_vxlan_set_rsc
rtnl_link_vxlan_get_rsc = _capi.rtnl_link_vxlan_get_rsc
rtnl_link_vxlan_enable_rsc = _capi.rtnl_link_vxlan_enable_rsc
rtnl_link_vxlan_disable_rsc = _capi.rtnl_link_vxlan_disable_rsc
rtnl_link_vxlan_set_l2miss = _capi.rtnl_link_vxlan_set_l2miss
rtnl_link_vxlan_get_l2miss = _capi.rtnl_link_vxlan_get_l2miss
rtnl_link_vxlan_enable_l2miss = _capi.rtnl_link_vxlan_enable_l2miss
rtnl_link_vxlan_disable_l2miss = _capi.rtnl_link_vxlan_disable_l2miss
rtnl_link_vxlan_set_l3miss = _capi.rtnl_link_vxlan_set_l3miss
rtnl_link_vxlan_get_l3miss = _capi.rtnl_link_vxlan_get_l3miss
rtnl_link_vxlan_enable_l3miss = _capi.rtnl_link_vxlan_enable_l3miss
rtnl_link_vxlan_disable_l3miss = _capi.rtnl_link_vxlan_disable_l3miss
RTNL_BRIDGE_HAIRPIN_MODE = _capi.RTNL_BRIDGE_HAIRPIN_MODE
RTNL_BRIDGE_BPDU_GUARD = _capi.RTNL_BRIDGE_BPDU_GUARD
RTNL_BRIDGE_ROOT_BLOCK = _capi.RTNL_BRIDGE_ROOT_BLOCK
RTNL_BRIDGE_FAST_LEAVE = _capi.RTNL_BRIDGE_FAST_LEAVE
rtnl_link_is_bridge = _capi.rtnl_link_is_bridge
rtnl_link_bridge_has_ext_info = _capi.rtnl_link_bridge_has_ext_info
rtnl_link_bridge_set_port_state = _capi.rtnl_link_bridge_set_port_state
rtnl_link_bridge_get_port_state = _capi.rtnl_link_bridge_get_port_state
rtnl_link_bridge_set_priority = _capi.rtnl_link_bridge_set_priority
rtnl_link_bridge_get_priority = _capi.rtnl_link_bridge_get_priority
rtnl_link_bridge_set_cost = _capi.rtnl_link_bridge_set_cost
rtnl_link_bridge_get_cost = _capi.rtnl_link_bridge_get_cost
rtnl_link_bridge_unset_flags = _capi.rtnl_link_bridge_unset_flags
rtnl_link_bridge_set_flags = _capi.rtnl_link_bridge_set_flags
rtnl_link_bridge_get_flags = _capi.rtnl_link_bridge_get_flags
rtnl_link_bridge_flags2str = _capi.rtnl_link_bridge_flags2str
rtnl_link_bridge_str2flags = _capi.rtnl_link_bridge_str2flags
rtnl_link_inet_devconf2str = _capi.rtnl_link_inet_devconf2str
rtnl_link_inet_str2devconf = _capi.rtnl_link_inet_str2devconf
rtnl_link_inet_set_conf = _capi.rtnl_link_inet_set_conf
tc_str2handle = _capi.tc_str2handle
rtnl_tc_set_ifindex = _capi.rtnl_tc_set_ifindex
rtnl_tc_get_ifindex = _capi.rtnl_tc_get_ifindex
rtnl_tc_set_link = _capi.rtnl_tc_set_link
rtnl_tc_get_link = _capi.rtnl_tc_get_link
rtnl_tc_set_mtu = _capi.rtnl_tc_set_mtu
rtnl_tc_get_mtu = _capi.rtnl_tc_get_mtu
rtnl_tc_set_mpu = _capi.rtnl_tc_set_mpu
rtnl_tc_get_mpu = _capi.rtnl_tc_get_mpu
rtnl_tc_set_overhead = _capi.rtnl_tc_set_overhead
rtnl_tc_get_overhead = _capi.rtnl_tc_get_overhead
rtnl_tc_set_linktype = _capi.rtnl_tc_set_linktype
rtnl_tc_get_linktype = _capi.rtnl_tc_get_linktype
rtnl_tc_set_handle = _capi.rtnl_tc_set_handle
rtnl_tc_get_handle = _capi.rtnl_tc_get_handle
rtnl_tc_set_parent = _capi.rtnl_tc_set_parent
rtnl_tc_get_parent = _capi.rtnl_tc_get_parent
rtnl_tc_set_kind = _capi.rtnl_tc_set_kind
rtnl_tc_get_kind = _capi.rtnl_tc_get_kind
rtnl_tc_get_stat = _capi.rtnl_tc_get_stat
rtnl_tc_calc_txtime = _capi.rtnl_tc_calc_txtime
rtnl_tc_calc_bufsize = _capi.rtnl_tc_calc_bufsize
rtnl_tc_calc_cell_log = _capi.rtnl_tc_calc_cell_log
rtnl_tc_read_classid_file = _capi.rtnl_tc_read_classid_file
rtnl_tc_handle2str = _capi.rtnl_tc_handle2str
rtnl_classid_generate = _capi.rtnl_classid_generate
qdisc2obj = _capi.qdisc2obj
obj2qdisc = _capi.obj2qdisc
class2obj = _capi.class2obj
obj2class = _capi.obj2class
cls2obj = _capi.cls2obj
obj2cls = _capi.obj2cls
obj2tc = _capi.obj2tc
rtnl_qdisc_alloc = _capi.rtnl_qdisc_alloc
rtnl_qdisc_get = _capi.rtnl_qdisc_get
rtnl_qdisc_get_by_parent = _capi.rtnl_qdisc_get_by_parent
rtnl_qdisc_build_add_request = _capi.rtnl_qdisc_build_add_request
rtnl_qdisc_add = _capi.rtnl_qdisc_add
rtnl_qdisc_build_update_request = _capi.rtnl_qdisc_build_update_request
rtnl_qdisc_update = _capi.rtnl_qdisc_update
rtnl_qdisc_build_delete_request = _capi.rtnl_qdisc_build_delete_request
rtnl_qdisc_delete = _capi.rtnl_qdisc_delete
rtnl_cls_alloc = _capi.rtnl_cls_alloc
rtnl_cls_put = _capi.rtnl_cls_put
rtnl_cls_add = _capi.rtnl_cls_add
rtnl_cls_delete = _capi.rtnl_cls_delete
rtnl_cls_set_prio = _capi.rtnl_cls_set_prio
rtnl_cls_get_prio = _capi.rtnl_cls_get_prio
rtnl_cls_set_protocol = _capi.rtnl_cls_set_protocol
rtnl_cls_get_protocol = _capi.rtnl_cls_get_protocol
rtnl_htb_get_rate2quantum = _capi.rtnl_htb_get_rate2quantum
rtnl_htb_set_rate2quantum = _capi.rtnl_htb_set_rate2quantum
rtnl_htb_get_defcls = _capi.rtnl_htb_get_defcls
rtnl_htb_set_defcls = _capi.rtnl_htb_set_defcls
rtnl_htb_get_prio = _capi.rtnl_htb_get_prio
rtnl_htb_set_prio = _capi.rtnl_htb_set_prio
rtnl_htb_get_rate = _capi.rtnl_htb_get_rate
rtnl_htb_set_rate = _capi.rtnl_htb_set_rate
rtnl_htb_get_ceil = _capi.rtnl_htb_get_ceil
rtnl_htb_set_ceil = _capi.rtnl_htb_set_ceil
rtnl_htb_get_rbuffer = _capi.rtnl_htb_get_rbuffer
rtnl_htb_set_rbuffer = _capi.rtnl_htb_set_rbuffer
rtnl_htb_get_cbuffer = _capi.rtnl_htb_get_cbuffer
rtnl_htb_set_cbuffer = _capi.rtnl_htb_set_cbuffer
rtnl_htb_get_quantum = _capi.rtnl_htb_get_quantum
rtnl_htb_set_quantum = _capi.rtnl_htb_set_quantum
rtnl_htb_get_level = _capi.rtnl_htb_get_level
addr2obj = _capi.addr2obj
obj2addr = _capi.obj2addr
rtnl_addr_alloc = _capi.rtnl_addr_alloc
rtnl_addr_get = _capi.rtnl_addr_get
rtnl_addr_build_add_request = _capi.rtnl_addr_build_add_request
rtnl_addr_add = _capi.rtnl_addr_add
rtnl_addr_build_delete_request = _capi.rtnl_addr_build_delete_request
rtnl_addr_delete = _capi.rtnl_addr_delete
rtnl_addr_flags2str = _capi.rtnl_addr_flags2str
rtnl_addr_str2flags = _capi.rtnl_addr_str2flags
rtnl_addr_set_label = _capi.rtnl_addr_set_label
rtnl_addr_get_label = _capi.rtnl_addr_get_label
rtnl_addr_set_ifindex = _capi.rtnl_addr_set_ifindex
rtnl_addr_get_ifindex = _capi.rtnl_addr_get_ifindex
rtnl_addr_set_link = _capi.rtnl_addr_set_link
rtnl_addr_get_link = _capi.rtnl_addr_get_link
rtnl_addr_set_family = _capi.rtnl_addr_set_family
rtnl_addr_get_family = _capi.rtnl_addr_get_family
rtnl_addr_set_prefixlen = _capi.rtnl_addr_set_prefixlen
rtnl_addr_get_prefixlen = _capi.rtnl_addr_get_prefixlen
rtnl_addr_set_scope = _capi.rtnl_addr_set_scope
rtnl_addr_get_scope = _capi.rtnl_addr_get_scope
rtnl_addr_set_flags = _capi.rtnl_addr_set_flags
rtnl_addr_unset_flags = _capi.rtnl_addr_unset_flags
rtnl_addr_get_flags = _capi.rtnl_addr_get_flags
rtnl_addr_set_local = _capi.rtnl_addr_set_local
rtnl_addr_get_local = _capi.rtnl_addr_get_local
rtnl_addr_set_peer = _capi.rtnl_addr_set_peer
rtnl_addr_get_peer = _capi.rtnl_addr_get_peer
rtnl_addr_set_broadcast = _capi.rtnl_addr_set_broadcast
rtnl_addr_get_broadcast = _capi.rtnl_addr_get_broadcast
rtnl_addr_set_multicast = _capi.rtnl_addr_set_multicast
rtnl_addr_get_multicast = _capi.rtnl_addr_get_multicast
rtnl_addr_set_anycast = _capi.rtnl_addr_set_anycast
rtnl_addr_get_anycast = _capi.rtnl_addr_get_anycast
rtnl_addr_get_valid_lifetime = _capi.rtnl_addr_get_valid_lifetime
rtnl_addr_set_valid_lifetime = _capi.rtnl_addr_set_valid_lifetime
rtnl_addr_get_preferred_lifetime = _capi.rtnl_addr_get_preferred_lifetime
rtnl_addr_set_preferred_lifetime = _capi.rtnl_addr_set_preferred_lifetime
rtnl_addr_get_create_time = _capi.rtnl_addr_get_create_time
rtnl_addr_get_last_update_time = _capi.rtnl_addr_get_last_update_time


